[package]
name = "vimm-downloader"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
scraper = "0.20"
anyhow = "1.0"
indicatif = "0.17"
sevenz-rust = "0.6"
zip = "2.2"
